// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '2.2.0'
    repositories {
        google()
        mavenCentral() // Add this line
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // Removed groovy-android-gradle-plugin as it's deprecated and not needed


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral() // Add this line here too, if you have an allprojects block
        maven {
            url "https://jitpack.io"

        }
        maven {
            url "https://maven.google.com"
            name 'Google'
        }
        google()
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
