apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'


android {
    namespace "ch.abertschi.adfree"
    compileSdkVersion 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    defaultConfig {
        applicationId "ch.abertschi.adfree"
        minSdkVersion 24
        targetSdkVersion 36
        versionCode 42
        versionName "3.2"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
   }


    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets {
        main { res.srcDirs = ['src/main/res', 'src/main/values-large/'] }
        test {
            java.srcDirs = ['src/test/java', 'src/test/groovy']
        }
        debug { java.srcDirs = ['src/debug/java', 'src/test/groovy/'] }
    }
    lint {
        abortOnError false
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation('androidx.test.espresso:espresso-core:3.6.1', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'androidx.appcompat:appcompat:1.7.1'

//    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.13.2'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    implementation 'com.google.android.material:material:1.12.0'

    implementation 'com.github.kittinunf.fuel:fuel:2.3.1'
    implementation 'com.github.kittinunf.fuel:fuel-android:2.3.1'

    implementation 'com.github.bmoliveira:snake-yaml:1.18.1-android-rc2'

    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'

    implementation 'io.reactivex.rxjava2:rxjava:2.2.21'

    implementation('com.thoughtworks.xstream:xstream:1.4.21') {
        exclude group: 'xmlpull', module: 'xmlpull'
    }

    testImplementation 'org.codehaus.groovy:groovy:3.0.19:grooid'
    testImplementation('org.spockframework:spock-core:2.3-groovy-3.0') {
        exclude group: 'org.codehaus.groovy'
        exclude group: 'junit'
    }

    testImplementation 'org.mockito:mockito-core:5.10.0'

    testImplementation 'org.mockito:mockito-android:5.10.0'
}
repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}
